config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/movies', to: 'movies#index', as: :movies

  get '/movies/new', to: 'movies#new', as: :new_movie
  patch '/movies', to: 'movies#create'

  get '/movies/:id', to: 'movies#show', as: :movie
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  validates :title, uniqueness: true
  validates :overview, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to movies_path(@movie)
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container mt-5">
  <h1>Movies</h1>
    <ul>
    <% @movies.each do |movie|%>
   <li> <%= link_to movie.title, movie_path(movie.id) %> </li>
    <% end %>
    </ul>
    <div class="actions">
    <br>
     <button><%= link_to "Add a new movie to list", new_movie_path %></button>
    </div>
</div>

app/views/movies/new.html.erb
<div class="container mt-5">
  <h1>Add a new Movie</h1>
   <%= simple_form_for(@movie) do |m| %>
  <%= m.input :title %>
  <%= m.input :overview %>
  <%= m.input :poster_url %>
  <%= m.input :rating %>
  <%= m.submit %>
<% end %>
 <div class="actions">
    <br>
     <button><%= link_to "Back to main page", movies_path %></button>
    </div>
</div>

app/views/movies/show.html.erb
<div class="container mt-5">
    <h1><%= @movie.title%></h1>
    <hr>
    <div class="wrapper">
      <h3><%= "Rating: #{@movie.rating}"%></h3>
      <div class="description">
        <h2 class="description__title">Overview</h2>
        <div class="description__body">
          <h3><%= @movie.overview%></h3>
        </div>
      </div>
      <%= image_tag @movie.poster_url, width: '300' %>
    </div>
    <div class="actions">
    <br>
     <button><%= link_to "Back to main page", movies_path %></button>
    </div>
</div>